program = statementlist <<eof>> ;

FIRST(program) = { '<', '>', '+', '-', '[', ε }
FOLLOW(program) = {}

statementlist = statement statementlist | ε ;

statement
    =   '<' 
    |   '>'
    |   '+'
    |   '-'
    |   '.'
    |   ','
    |   loop
    ;

loop
    = '[' , statementlist , ']'
    ;